name: Gitee Sync
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 16 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: sync
        uses: sunn4room/gitee-sync-action@main
        with:
          username: ${{ secrets.GITEE_USERNAME }}
          password: ${{ secrets.GITEE_PASSWORD }}
          repositories: |
            sunn4mirror
            sunn4import
